defaults: &defaults

  # sites hosts
  # session expire seconds
  # admin role account
  URL_HOST: bitking.com.tw
  URL_SCHEMA: http
  SESSION_EXPIRE: 120
  API_WHITELIST: []
  ADMIN: 'netwareboss@gmail.com'
  TIMEZONE: 'Beijing'
  REDIS_URL: redis://59.127.216.102:6379
  # below settings only in production env
  # system notify mail settings
  # --------------------------------------------------------------
  SMTP_DOMAIN: smtp.gmail.com
  SMTP_ADDRESS: smtp.gmail.com
  SMTP_USERNAME: twbitking
  SMTP_PASSWORD: x6359338

  SYSTEM_MAIL_FROM: twbitking@gmail.com
  SYSTEM_MAIL_TO: twbitking@gmail.com

  # WebSocket Streaming API settings
  WEBSOCKET_HOST: 0.0.0.0
  WEBSOCKET_PORT: 8080
  # Uncomment below to enable secure WebSocket (wss)
  #WEBSOCKET_SSL_KEY: 'your_server.key'
  #WEBSOCKET_SSL_CERT: 'your_server.crt'

  # recaptcha settings
  # --------------------------------------------------------------
  # in exchange some operation need validate operator is not bot.
  # peatio use RECAPTCHA validate this
  # so you need apply a new key or use we support development key
  # uncomment below line only development or test
  #
  # RECAPTCHA_PUBLIC_KEY: 6LfxHegSAAAAAOD6mQ1PFvXgBApsHl_oO_y9EtI9
  # RECAPTCHA_PRIVATE_KEY: 6LfxHegSAAAAAH4M8CuhJJoH8VGYswg2HI_xY5N1

  RECAPTCHA_PUBLIC_KEY: 6Le_PPISAAAAALW1q0XSaBTesw1ukrbUuwBXV6rD
  RECAPTCHA_PRIVATE_KEY: 6Le_PPISAAAAACgxu5KNVvt90yHBn9sO6m3yGMO5


  # pusher settings
  # --------------------------------------------------------------
  # peatio dependence Pusher (http://pusher.com) service
  # you can change your key for production environment.
  # we support development key and secret
  # uncomment below line only development or test
  #
  # PUSHER_APP: 65910
  # PUSHER_KEY: 50d404c35db92d736a57
  # PUSHER_SECRET: 75d6e6685209cc60cc4d

  PUSHER_APP: 71777
  PUSHER_KEY: da4e7662daf07d5356e4
  PUSHER_SECRET: 8fb345919cf93d8e3bb7
  PUSHER_HOST: api.pusherapp.com
  PUSHER_PORT: 80
  PUSHER_WS_PORT: 80
  PUSHER_WSS_PORT: 443
  PUSHER_ENCRYPTED: true

  # twilio setting
  # --------------------------------------------------------------
  # https://github.com/twilio/twilio-ruby
  #
  TWILIO_NUMBER: YOUR_TWILIO_NUMBER
  TWILIO_SID: YOUR_TWILIO_SID
  TWILIO_TOKEN: YOUR_TWILIO_TOKEN

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
